### ISSUE TITLE
Should the order match the GNU --group-directories-first?

### ISSUE THREAD

**Issue by dactylo** [torstenvl/betterls#1]
Hey thanks for putting this up.

Seems like this might be intentional but for the record- the order is slightly different than the GNU `--group-directories-first`, which puts all directories first, e.g.:

- The special . and .. files.
- The dot dirs.
- The non-dotted dirs.
- The dot files.
- The non-dotted files.

That is pretty close to the Finder alphanumeric sort, though if we're trying to match that, the Finder seems to put _ before anything else.

**Comment by torstenvl** [comment]
Thanks! I like all 'hidden' files and directories visible, but a little out of the way, so that's why the original behavior was like that. I added another flag, --group-dots-extra-first, for myself (and those who might share my preference).

**Comment by dactylo** [comment]
Awesome, thanks for the quick change!

I remember wanting this several years ago. There must be a lot of other people out there as well, so hopefully they'll discover this repo eventually.
